export const hotelTypes = [
    "Hotel",
    "Hostel",
    "Guest House",
    "Apartment",
    "Resort",
    "Villa",
    "Inn",
    "Cottage",
    "Bungalow",
    "Cabin",
    "Boat",
    "House",
    "Dormitory",
    "Tent",
    "Lodge",
    "Yurt",
    "Caravan",
    "Tiny House",
    "Farm stay",
    "Other",
];


export const hotelFacilities = [
    "Free Wi-Fi",
    "Free parking",
    "Room service",
    "Bar",
    "Swimming pool",
    "Airport shuttle",
    "Spa",
    "Fitness center",
    "Pet friendly",
    "Family rooms",
    "Restaurant",
    "Terrace",
    "Garden",
    "Elevator",
    "Tour desk",
]